# Arquivo de Configuração do MarriageMaster

# Idioma
Language:
  # Define o idioma utilizado e o arquivo correspondente. O arquivo de idioma correspondente será colocado ao lado do config.yml com o nome: <Language>.yml
  Language: br
  # Opções:
  #     Overwrite (apaga todas as alterações do arquivo e extrai um novo arquivo de idioma)
  #     Upgrade (extrai um novo arquivo de idioma e copia todas as configurações do arquivo de idioma antigo)
  #     Update (adiciona os valores de texto padrão (inglês) para todos os valores ausentes, apenas uma formatação básica)
  UpdateMode: Upgrade

# Configurações de Banco de Dados
Database:
  # SQLite = dados armazenados em arquivo SQLite, MySQL = dados armazenados em banco de dados MySQL (veja a seleção abaixo), Shared = usar pool de conexão compartilhada do PCGF PluginLib
  Type: SQLite
  # Define o formato de armazenamento para UUIDs para compatibilidade com outros plugins (tabela de usuários compartilhada).
  # true: formato: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  # false: formato: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  UseUUIDSeparators: false
  # Opções: auto, online, offline | auto decidirá com base na opção de modo online do servidor.
  # Se você estiver usando BungeeCord, defina para o que quer que use no seu servidor BungeeCord!!!
  UUID_Type: auto
  SQL:
    Host: 'localhost'
    Database: 'minecraft'
    User: 'minecraft'
    Password: 'minecraft'
    # A quantidade máxima de conexões com o banco de dados que o pool de conexões abrirá.
    # Você pode querer ajustar esta configuração com base na carga do seu servidor de banco de dados e na quantidade de jogadores.
    MaxConnections: 2
    # Permite definir as propriedades de conexão.
    # Propriedades: ["useSSL=false"]
    Properties: []
    Tables:
      User: marry_players
      Partner: marry_partners
      Home: marry_home
      Priests: marry_priests
  # Configurações que controlam o comportamento do cache do plugin. Você pode otimizá-lo um pouco dependendo da contagem de jogadores, ram ou gargalos de cpu.
  Cache:
    UnCache:
      # A estratégia usada para remover jogadores offline do cache. Opções:
      #     interval (jogadores offline são removidos do cache a cada x segundos)
      #     intervalChecked (como o interval, mas também garante que o jogador já esteja offline por pelo menos o tempo do intervalo)
      #     ondisconnect (o jogador é removido do cache instantaneamente assim que se desconecta do servidor, pode adicionar sobrecarga se outros plugins tentarem acessar os dados do jogador quando eles ficarem offline, também pode ser problemático para jogadores com conexões instáveis)
      #     ondisconnectdelayed (o jogador é removido do cache x segundos depois de ficar offline, adiciona sobrecarga ao desconectar, você não deve usar isso com muitos jogadores entrando e saindo.)
      Strategy: interval
      # Usado para os algoritmos de remoção de cache baseados em intervalo. Também usado como atraso para ondisconnectdelayed. Valor em segundos. Padrão: 600 = 10 minutos
      Interval: 600
      Delay: 600

Marriage:
  # Define se os jogadores precisam ser casados por um padre ou se podem casar entre si por conta própria.
  RequirePriest: true
  # Esta opção define se um padre é necessário para divorciar 2 jogadores ou se eles podem divorciar-se por conta própria.
  # Opções: true, false, auto (auto copiará o valor de RequirePriest)
  DivorceRequiresPriest: auto
  # Número máximo de parceiros que um jogador pode ter. Valores < 1 desativam o limite.
  MaxPartners: 1
  # Esta configuração desativa o comando "/marry setpriest". Os jogadores ainda podem ser promovidos a padre com a permissão "marry.priest".
  DisableSetPriestCommand: false
  Surnames:
    Enable: false
    Force: false
    # Requisitos de sobrenome
    AllowColors: false
    AllowedCharacters: A-Za-z
    BannedNames: []
    # Valores abaixo de 3 serão definidos como 3
    MinLength: 3
    # Valores abaixo do comprimento mínimo serão definidos como o comprimento mínimo
    MaxLength: 16
    # Opções: None, Player, BothPlayers
    Confirmation: None
  # Define se os casamentos devem ser anunciados a todos os jogadores.
  AnnounceOnMarriage: true
  # Define se os divórcios devem ser anunciados a todos os jogadores. auto espelha a configuração AnnounceOnMarriage
  AnnounceOnDivorce: auto
  Confirmation:
    Enable: true
    AutoDialog: true
    BothPlayersOnDivorce: false
    OtherPlayerOnSelfDivorce: false

InfoOnPartnerJoinLeave:
  Enable: true
  # Atraso para informações de parceiros online ao entrar. Em segundos
  JoinDelay: 0

# As opções de prefixo/sufixo não funcionam com todos os plugins de chat!
# Se o seu plugin de chat suportar APIs de placeholder, seria melhor usá-las! Mais detalhes: https://github.com/GeorgH93/MarriageMaster/wiki/Placeholders
Prefix:
  Enable: false
  # Espaços reservados: {Surname}, {PartnerName}, {PartnerDisplayName}, {StatusHeart}, {MagicHeart}
  String: "<heart>{PartnerName}<heart>"
  OnLineBeginning: true
Suffix:
  Enable: false
  # Espaços reservados: {Surname}, {PartnerName}, {PartnerDisplayName}, {StatusHeart}, {MagicHeart}
  String: "{Surname}"

Gift:
  Enable: true
  AllowedGameModesAllowed: [ "SURVIVAL" ]
  AllowedGameModesReceive: [ "SURVIVAL" ]
  # Lista de mundos onde os jogadores não podem receber presentes
  BlacklistedWorlds: []
  # Se esta opção estiver habilitada, o parceiro terá que aceitar o presente.
  RequireConfirmation: false
  ItemFilter:
    # Ativa o filtro de itens. Certifique-se de definir os itens a serem filtrados.
    Enabled: false
    # Altera o modo do filtro, seja lista negra (apenas materiais não listados são permitidos) ou lista branca (apenas materiais listados são permitidos)
    Mode: blacklist
    # Listas de filtros abaixo. Um item será bloqueado (no modo lista negra) ou permitido (no modo lista branca) se corresponder a um dos filtros fornecidos.
    # Lista de materiais que devem ser filtrados. Pode ser nome ou id (id apenas para versões do MC anteriores a 1.13!).
    Materials: [ ]
    # Lista de nomes que devem ser filtrados. Deve corresponder exatamente ao nome de exibição do item. Códigos de cor & serão convertidos automaticamente.
    Names: [ ]
    # Lista de lore que deve ser filtrada. Pode ser uma única linha ou todas as linhas da lore.
    Lore: [ ]

Kiss:
  # Ativa o comando de beijo
  Enable: true
  # Ativa o beijo ao agachar + clique direito
  EnableInteract: true
  # Tempo entre dois beijos em segundos, 0 para desativar o cooldown
  WaitTime: 10
  # Quantos corações devem ser gerados
  HearthCount: 50

Hug:
  # Ativa o comando de abraço
  Enable: true
  # Tempo entre dois abraços em segundos, 0 para desativar o cooldown
  WaitTime: 10
  # Quantas partículas devem ser geradas, 0 para desativar
  ParticleCount: 25

List:
  UseFooter: true
  EntriesPerPage: 8

PvP:
  AllowBlocking: true

BonusXp:
  Enable: true
  # Valores menores ou iguais a 1 desativarão o xp bônus, mas ainda permitem dividir o xp entre os jogadores
  Multiplier: 2
  # Se habilitado, o xp coletado será dividido entre os dois jogadores. Assim, cada jogador receberá (xp * multiplicador / 2) xp
  SplitXpOnPickup: true
  # Se habilitado, o xp será dividido com todos os parceiros que estiverem ao alcance. Assim, cada jogador receberá (xp * multiplicador / quantidade_de_parceiros_ao_alcance) xp. Requer que SplitXpOnPickup esteja habilitado.
  SplitWithAllPartnersInRange: false
  SkillAPI:
    Enable: false
    # Lista de fontes que devem ser excluídas do bônus de xp. A fonte do comando é sempre excluída!
    ExcludeSources: []
    Multiplier: 2
    # Se a divisão estiver habilitada, o valor multiplicado será dividido entre os dois parceiros. Assim, cada jogador receberá (xp * multiplicador / 2) xp
    SplitXp: true
    # Se habilitado, o xp será dividido com todos os parceiros que estiverem ao alcance. Assim, cada jogador receberá (xp * multiplicador / quantidade_de_parceiros_ao_alcance) xp. Requer que SplitXp esteja habilitado.
    SplitWithAllPartnersInRange: false
  McMMO:
    Enable: false
    Multiplier: 2
    # Se a divisão estiver habilitada, o valor multiplicado será dividido entre os dois parceiros. Assim, cada jogador receberá (xp * multiplicador / 2) xp
    SplitXp: true
    # Se habilitado, o xp será dividido com todos os parceiros que estiverem ao alcance. Assim, cada jogador receberá (xp * multiplicador / quantidade_de_parceiros_ao_alcance) xp. Requer que SplitXp esteja habilitado.
    SplitWithAllPartnersInRange: false
    # Lista de fontes que devem ser excluídas do bônus de xp.
    ExcludeSources: [ "COMMAND" ]
    # Lista de habilidades que devem ser excluídas do bônus de xp.
    ExcludeSkills: []
  AuraSkills:
    Enable: false
    # Lista de fontes que devem ser excluídas do bônus de xp. A fonte do comando é sempre excluída!
    ExcludeSources: []
    ExcludeSkills: []
    Multiplier: 2
    # Se a divisão estiver habilitada, o valor multiplicado será dividido entre os dois parceiros. Assim, cada jogador receberá (xp * multiplicador / 2) xp
    SplitXp: true
    # Se habilitado, o xp será dividido com todos os parceiros que estiverem ao alcance. Assim, cada jogador receberá (xp * multiplicador / quantidade_de_parceiros_ao_alcance) xp. Requer que SplitXp esteja habilitado.
    SplitWithAllPartnersInRange: false
  Jobs:
    Enable: false
    Multiplier: 2
    SplitXp: true
    ExcludeJobs: []

HealthRegain:
  Enable: true
  Multiplier: 2
  # Lista de mundos onde os jogadores não podem receber bônus de regeneração de saúde
  BlacklistedWorlds: []

Chat:
  Enabled: true
  AllowSurveillance: false

# Alcances para as ações
# -1 sem limite de alcance e sem limite de mundo, 0 sem limite de alcance mas no mesmo mundo, >= 1 limite de alcance em metros/blocos
Range:
  Marry: 25
  Divorce: 25
  Backpack: 5
  Gift: 0
  Kiss: 2
  KissInteract: 5
  Hug: 2
  HearthVisible: 128
  HugParticleVisible: 128
  BonusXP: 10
  Heal: 3

# Estas configurações serão usadas para todos os teletransportes (home e para parceiro)
Teleport:
  Delay: false
  # Tempo em segundos
  DelayTime: 3
  # Lista de mundos para onde você pode/não pode se teleportar (com base no FilterMode)
  FilteredWorlds: []
  # Define como os mundos filtrados (FilteredWorlds) serão tratados, block = impede os jogadores de se teleportarem para esses mundos; allow = permite que os jogadores se teleportem apenas para esses mundos
  FilterMode: "block"
  # Esta opção controla se uma verificação de segurança é realizada antes que o jogador seja teleportado.
  CheckSafety: true
  # Esta opção controla se o plugin tenta encontrar um local seguro se a verificação de segurança falhar. Habilitar isso pode permitir que o jogador atravesse paredes.
  FindSafeLocation: false
  # Se esta opção estiver habilitada, o parceiro terá que aceitar o pedido de teletransporte antes que o jogador seja teleportado. Aplicável apenas para teletransporte para outro jogador.
  RequireConfirmation: false

# Opções de configuração para compartilhar mochilas entre parceiros
# Atualmente, o único plugin de mochila suportado é o Minepacks
BackpackShare:
  # Ativa o recurso de compartilhamento de mochila (com plugins suportados)
  Enable: true

Economy:
  Enable: false
  # Cada um dos dois jogadores terá que pagar metade do valor. Exemplo: custo=100 -> o jogador_a tem que pagar 50 e o jogador_b tem que pagar 50
  Marry: 100.0
  # Cada um dos dois jogadores terá que pagar metade do valor. Exemplo: custo=100 -> o jogador_a tem que pagar 50 e o jogador_b tem que pagar 50
  Divorce: 100.0
  Tp: 25.0
  Gift: 10.0
  HomeTp: 25.0
  SetHome: 100.0
  ChangeSurname: 0

# Permite a execução de comandos em certos eventos relacionados ao casamento
CommandExecutor:
  Enable: false
  # Informações gerais sobre o executor de comandos:
  # Os comandos podem conter espaços reservados no formato {PlaceholderName} (O {} faz parte do nome. Os espaços reservados disponíveis estão listados acima do evento).
  # Cada evento pode executar vários comandos na lista. Os comandos não precisam começar com / !
  # Comandos a serem executados:
  # Será executado quando dois jogadores se casarem, sem um padre
  # Espaços reservados permitidos: {Player1}, {Player2}
  # OnMarry: [ "eco give {Player1} 100", "pex user {Player2} add example.perm" ]
  OnMarry: []
  # Será executado quando dois jogadores se casarem por um padre
  # Espaços reservados permitidos: {Player1}, {Player2}, {Priest}
  OnMarryWithPriest: []
  # Será executado quando dois jogadores se divorciarem, sem um padre
  # Espaços reservados permitidos: {Player1}, {Player2}
  OnDivorce: []
  # Será executado quando dois jogadores se divorciarem através de um padre
  # Espaços reservados permitidos: {Player1}, {Player2}, {Priest}
  OnDivorceWithPriest: []

# O comando que deve ser usado se nenhum subcomando for utilizado.
# Opções: help (/marry help), custom_help (exibirá as mensagens definidas no arquivo de idioma em Language.Ingame.Help.CustomHelp)
DefaultCommand: "help"
# A cor do casamento é usada para o coração mágico/colorido e é definida como um valor aleatório por padrão.
AllowPlayersToChangeMarriageColor: true

Sound:
  # Configuração global se os sons devem ser usados. Cada efeito sonoro pode ser desativado individualmente definindo-o como 'DISABLED'.
  Enable: true
  Married: ORB_PICKUP
  Divorced: ORB_PICKUP

Misc:
  AutoUpdate:
    # Quando a atualização automática está desativada, você ainda pode usar a função de atualização integrada manualmente com /marry update
    Enable: true
    Channel: ${updateChannel}
  # Ative esta opção se estiver em um ambiente BungeeCord. Por favor, instale também o plugin no seu servidor BungeeCord para permitir que os dados sejam sincronizados em todos os seus servidores.
  UseBungeeCord: false

# Versão do arquivo de configuração. Não mexa!
Version: ${configFileVersion}
